# Generated by Django 4.1.4 on 2026-08-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "restaurant",
            "0003_remove_booking_comment_remove_booking_guest_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="reservation_slot",
            field=models.SmallIntegerField(
                choices=[
                    (10, "10:00"),
                    (11, "11:00"),
                    (12, "12:00"),
                    (13, "13:00"),
                    (14, "14:00"),
                    (15, "15:00"),
                    (16, "16:00"),
                    (17, "17:00"),
                    (18, "18:00"),
                    (19, "19:00"),
                ],
                default=10,
            ),
        ),
    ]
